/*------------------------------------------------------------------------------
 *******************************************************************************
 * COPYRIGHT Ericsson 2014
 *
 * The copyright to the computer program(s) herein is the property of
 * Ericsson Inc. The programs may be used and/or copied only with written
 * permission from Ericsson Inc. or in accordance with the terms and
 * conditions stipulated in the agreement/contract under which the
 * program(s) have been supplied.
 *******************************************************************************
 *----------------------------------------------------------------------------*/
package com.ericsson.oss.services.ap.model;

import java.io.Serializable;

import com.ericsson.oss.itpf.datalayer.dps.modeling.annotation.CanBeRoot;
import com.ericsson.oss.itpf.datalayer.dps.modeling.annotation.Hierarchical;
import com.ericsson.oss.itpf.datalayer.dps.modeling.annotation.OnReadWrite;
import com.ericsson.oss.itpf.datalayer.dps.modeling.annotation.PrimaryTypeAttribute;
import com.ericsson.oss.itpf.datalayer.dps.modeling.annotation.PrimaryTypeDefinition;
import com.ericsson.oss.itpf.datalayer.dps.modeling.annotation.WriteBehavior;
import com.ericsson.oss.itpf.modeling.annotation.EModel;
import com.ericsson.oss.itpf.modeling.annotation.EModelAttribute;
import com.ericsson.oss.itpf.modeling.annotation.LifeCycle;
import com.ericsson.oss.itpf.modeling.annotation.LifeCycleState;
import com.ericsson.oss.itpf.modeling.annotation.constraints.NotNull;

/**
 * Defines an Auto Provisioning Project.
 */
@EModel(namespace = "ap", description = "Auto Provisioning Project", name = "Project", version = ApVersion.PROJECT_VERSION)
@PrimaryTypeDefinition()
@Hierarchical(canBeRoot = CanBeRoot.TRUE, parentMoTypeUrn = "")
@OnReadWrite(onWrite = WriteBehavior.WRITE_TO_PERSISTENT_STORAGE_ONLY)
public class Project implements Serializable {

    private static final long serialVersionUID = 1L;

    @PrimaryTypeAttribute
    @EModelAttribute(description = "The ID of the Project MO, typically the name of the AP project", key = true, immutable = true, mandatory = true)
    @NotNull
    public String ProjectId;

    @EModelAttribute(description = "User ID of the project creator", mandatory = false, immutable = true)
    @PrimaryTypeAttribute
    public String creator;

    @EModelAttribute(description = "A description of the project")
    @PrimaryTypeAttribute
    public String description;

    @EModelAttribute(description = "Provisioning tool that this project is generated by", mandatory = false)
    @PrimaryTypeAttribute
    public String generatedby;

    @EModelAttribute(description = "Date that this project was created in the DB", mandatory = true, immutable = true)
    @PrimaryTypeAttribute
    public String creationDate;

    @EModelAttribute(description = "Specifies if the project is batch", mandatory = false, immutable = true)
    @PrimaryTypeAttribute
    @LifeCycle(value = LifeCycleState.OBSOLETE, lifeCycleDescription = "This attribute is no longer used")
    public String batch;
}
